name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: dev
            url: https://dev.gcn.nasa.gov
          - env: test
            url: https://test.gcn.nasa.gov
          - env: prod
            url: https://gcn.nasa.gov
    runs-on:
      - aws
      - ${{ matrix.env }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ matrix.url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Architect
        run: npm i -g @architect/architect@^10.3.2 aws-sdk
      - name: NPM Install
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Deploy
        run: arc deploy --prune --production
